name: app_cuu_ho
services:
  app:
    build: .
    container_name: app_cuu_ho_api_be
    restart: unless-stopped
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    image: postgres:16
    container_name: app_cuu_ho_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
